### ISSUE TITLE
Support Apple M1 Darwin ARM

### ISSUE THREAD

**Issue by poetaman** [yankeexe/air-quality-cli#6]
yankeexe/air-quality-cli crit platform darwin/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/yankeexe/air-quality-cli/issues/new

**Comment by yankeexe** [comment]
@reportaman I think this one should work on M1 Macbooks?
https://github.com/yankeexe/air-quality-cli/releases/download/v0.0.5/air-quality-cli_0.0.5_Darwin_arm64.tar.gz

**Comment by poetaman** [comment]
@yankeexe Yes! thanks it worked!

**Comment by yankeexe** [comment]
@reportaman awesome! 😄
